added apache2 installer if not installed

diff --git a/0x0D-web_stack_debugging_0/0-give_me_a_page b/0x0D-web_stack_debugging_0/0-give_me_a_page
--- a/0x0D-web_stack_debugging_0/0-give_me_a_page
+++ b/0x0D-web_stack_debugging_0/0-give_me_a_page
@@ -1,5 +1,9 @@
 #!/usr/bin/env bash
-#running docker id and change restart apache2o
-chmod 644 /var/www/html/index.html
+# running docker id and change restart apache2
+if ! command -v apache2 > /dev/null; then
+       echo  "Command not found! Installing apache2"
+       sudo apt-get -y install apache2
+fi
+sudo chmod 644 /var/www/html/index.html
 echo "Hello Holberton" > /var/www/html/index.html
-service apache2 start
+sudo service apache2 restart
